### ISSUE TITLE
右上角加号有bug

### ISSUE THREAD

**Issue by goxofy** [wuxiaocong/hermit-for-typecho#2]
例如设置了首页文章为6篇，打开首页后显示6篇，点击+号之后，会继续刷出6篇，但是继续点击加号，会直接刷出12篇，其中前6篇和后6篇为重复内容。

**Comment by wuxiaocong** [comment]
应该是网络问题，不过这个ajax加载方式着实有点鸡肋了，但因为感觉这样+ == 很酷，就没有去管了。

**Comment by goxofy** [comment]
应该不是阿，我在本地测试也是这样。。。

**Comment by wuxiaocong** [comment]
的缺是有这样的问题，等有空了再改改。

**Comment by goxofy** [comment]
好的坐等谢谢～
